name: Deploy to Railway (Wasp)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      WASP_VERSION: "0.21"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12"

      - name: Install Wasp CLI
        run: npm i -g @wasp.sh/wasp-cli@$WASP_VERSION

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy via Wasp
        run: |
            wasp deploy railway deploy flight-club-mage --existing-project-id ed2c40a5-1001-4a6f-8022-dab62b7ec9df
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
